#+TITLE: Ben Anhalt
#+AUTHOR: Ben Anhalt

#+OPTIONS: toc:nil num:nil date:nil ':t
#+MACRO: date @@latex: \hfill\normalfont{\small $1} @@ @@html: <div id=date>$1</div> @@ @@ascii: ($1) @@
#+MACRO: pagebreak @@latex: \clearpage @@

| [[https://con.cor.dance][con.cor.dance]] | [[mailto:ben@benanhalt.net][ben@benanhalt.net]] |

* Format                                                           :noexport:
** Latex
  Note: to manually fit content nicely to each page:
  - Add in a heading =** {{{pagebreak()}}}= (This will only effect pdf output)
  - Alter the value of \setlist{itemsep=??} (adjust spacing between bullet items)
  - Adjust the page margins (geometry package)

*** Page layout
    #+LATEX_CLASS_OPTIONS: [letterpaper,11pt]
    #+LATEX_HEADER: \usepackage[left=3cm, right=3cm, top=2.7cm, bottom=2.7cm]{geometry}
    #+LATEX_HEADER: \usepackage{parskip}
    #+LATEX_HEADER: \usepackage{microtype}
    #+LATEX_HEADER: \usepackage{enumitem}
    #+LATEX_HEADER: \setlist{itemsep=-3pt} % Vert space between items/bullets
    #+LATEX_HEADER: \setlist[itemize]{leftmargin=12pt}
    #+LATEX_HEADER: \renewcommand{\labelitemi}{$\bullet$}
    #+LATEX_HEADER: \usepackage{lastpage}
    #+LATEX_HEADER: \usepackage{fancyhdr}
    #+LATEX_HEADER: \pagestyle{fancy}
    #+LATEX_HEADER: \fancyhf{}
    #+LATEX_HEADER: \renewcommand{\headrulewidth}{0pt}
    #+LATEX_HEADER: \cfoot{Page \thepage\ of \pageref{LastPage}}
    #+LATEX_HEADER: \hypersetup{colorlinks=true,urlcolor=black,linkcolor=black}

*** Font
    #+LATEX_HEADER: \usepackage{lmodern}
    #+LATEX_HEADER: \usepackage{xcolor}
    #+LATEX_HEADER: \color[HTML]{333333}

*** Title format
    #+LATEX_HEADER: \usepackage{titling}
    #+LATEX_HEADER: \definecolor{myaccent}{HTML}{1C6AAF}
    #+LATEX_HEADER: \renewcommand{\maketitle}{{\centering {\color{myaccent}\huge\bfseries\theauthor}\par \vspace{4pt}}}

*** Heading format
    #+LATEX_HEADER: \usepackage{titlesec}
    #+LATEX_HEADER: \titleformat*{\section}{\sffamily\raggedright\footnotesize\bfseries\color{myaccent}\uppercase}
    #+LATEX_HEADER: \titleformat*{\subsection}{\raggedright\large\bfseries\color[HTML]{000000}}
    #+LATEX_HEADER: \titlespacing*{\section}{0pt}{20pt}{8pt}
    #+LATEX_HEADER: \titlespacing*{\subsection}{0pt}{20pt}{0pt}

** HTML
   #+HTML_HEAD: <link rel="stylesheet" type="text/css" href="stylesheet.css" />
   #+OPTIONS: html-postamble:nil

* Skills

  - *Languages*: Python, Javascript, Go, Java, Elm, Haskell, SQL, HTML, XML
  - *Libraries*: Django, SQLAlchemy, Celery, JQuery, Backbone.js
  - *Databases*: Postgres, MySQL, Solr
  - *Tools and Software*: Linux, Docker, Git, OpenAPI, Apache, Nginx
  - *Services*: Github, Digital Ocean, LetsEncrypt, Teams, Slack, Zoom
  - *Soft Skills*: Code Review, Agile, Mentoring, Hiring Committees, Customer
    Service

* Work Experience
** IT Specialist {{{date(Dec 2024 -- Feb 2025)}}}
   /[[https://www.fpacbc.usda.gov/geospatial-services][USDA -- Farm Production and Conservation Business Center -- Geospatial Services]]/
   
   - Member of Data Provisioning Team effecting migration of GIS service pipelines
     and data storage from on-prem to AWS cloud.
   - Obtained Public Trust clearance.
   - Successfully on-boarded into remote position with a federal agency.
   - Received training in ArcGIS products.
     
** Senior Cloud Backend Engineer {{{date(Nov 2022 -- Aug 2023)}}}
   /[[https://thread.one][Thread]] -- SaaS provider for energy utilities/

   - Individual contributor within cloud team of about 10 engineers.
   - Upgraded and enhanced existing web-based data management application according
     to user requirements.
   - Designed and implemented REST APIs in Go to be deployed to the AWS cloud hosted
     microservices back end.
   - Developed SQL queries and schema migrations for PostgreSQL databases.
   - Analyzed and resolved performance issues in SQL queries.
   - Developed unit and integration tests.
   - Implemented relationship-based authorization system (ReBAC).
   - Diagnosed and resolved user reported defects.
   - Participated in code reviews and Agile development methodology.
   - Communicated effectively within a remote, distributed team, utilizing Slack and
     Microsoft Teams.
   - Documented work in Architecture Decision Records (ADR) and entries in company
     knowledge base using Notion.

** Research Architect {{{date(Jan 2018 -- Nov 2022)}}}
   /[[https://specifysoftware.org][Specify Collections Consortium]]/

   - Lead developer for Specify, a not-for-profit, member supported software project
     within the Biodiversity Institute at the University of Kansas that provides
     open-source digital collection management software for biological research and
     natural history museum collections. Features include data ingestion, inventory,
     reporting, search, label creation, workflow processes, and on-prem and hosted
     cloud deployment options.
   - Collaborated with subject matter experts to determine user requirements.
   - Provided technical expertise regarding cloud services, software development
     best practices, including analysis and evaluation of open-source and COTS
     software libraries and tooling for use throughout the software development life
     cycle (SDLC).
   - Analyzed customer requirements to develop recommendations and proposals for new
     features and enhancements to existing applications, taking into account
     alternatives and cost-effectiveness.
   - Developed application and infrastructure architecture.
   - Coordinated software releases with an emphasis on CI/CD and reproducible builds
     utilizing Docker.
   - Participated in webinars to apprise stakeholders of project goals and gather
     feedback.
   - Authored architectural, technical, and operational documentation in wikis and
     support pages.
   - Served on hiring committees for developers which included formulating
     questions, participating in interviews, assessing code samples, and evaluating
     candidates.

** Research Engineer {{{date(2014 -- Jan 2018)}}}
   /[[https://biodiversity.ku.edu/][University of Kansas Biodiversity Institute]]/
   
   - Individual contributor on the Specify and Lifemapper projects including feature
     enhancements and issue resolution as part of a 3-4 member engineering team.
   - Led full-stack development of the Specify 7 web application, developing and
     maintaining Django based backend providing REST APIs and business logic, and JS
     single page application (SPA) frontend.
   - Developed related cloud services for digital asset management and full-text
     search.
   - Monitored cloud infrastructure for performance and stability.
   - Supported end users via email and screen sharing.
   - Worked independently to design, implement, test, and merge new components based
     on issue tracking in Github using Agile methodology.
   - Performed data migrations between systems with different schemas, utilizing SQL
     and Python scripts.
   - Managed operation infrastructure including MySQL, Apache Solr, Apache HTTP
     server, and Nginx services in on-site installations and cloud VMs at Digital
     Ocean.
   - Represented the project in a technical capacity at international conferences.

** Programmer I {{{date(2011 -- 2014)}}}
   /[[https://biodiversity.ku.edu/][University of Kansas Biodiversity Institute]]/
   
   - Individual contributor on the Specify project.
   - Delivered new features and enhancements and resolved issues in existing Specify
     6 Java desktop application.
   - Took initiative in launching development of new Specify 7 web-based
     application, leveraging existing MySQL database schema to provide
     backward-compatible upgrade path for users.
   - Migrated version control for large codebase from SVN to Git.
   - Took part in subject matter conferences to demo new features and gather user
     requirements and feedback.
     
* Education
** Master of Science -- Physics
   /University of Kansas/

   - Investigated optimization strategies for nonlinear beam-beam interactions in
     the Tevatron particle accelerator.
   - Developed code in C++ and Fortran to model and simulate beam-beam interactions.

** Bachelor of Science -- Physics, Mathematics
   /Missouri State University/

   - Magna Cum Laude in the Honors College
   - GPA: 3.8
